EdSurvey/EdSurvey/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from home.views import index as homepage
from clients.views import log_in, log_out

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', homepage, name='homepage'),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^login$', log_in, name='login'),
    url(r'^logout$', log_out, name='logout'),
    url(r'^clients/', include('clients.urls', namespace='clients')),
    url(r'^questions/', include('questions.urls', namespace='questions')),
    url(r'^querylists/', include('querylists.urls', namespace='querylists')),
    url(r'^schedules/', include('schedules.urls', namespace='schedules')),
]

EdSurvey/clients/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^$', views.index),
    url(r'^aka$', views.aka, name='aka'),
]

EdSurvey/home/urls.py
from django.conf.urls import url, include

from . import views

#   home.urls


urlpatterns = [
    url(r'^$', views.index),
]

EdSurvey/schedules/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^task$', views.task_index, name='task'),
    url(r'^edittask/(?P<taskid>\d+)$', views.edit_task, name='edittask'),
    url(r'^newtask$', views.new_task, name='newtask'),
    url(r'^schedule$', views.schedule_index, name='schedule'),
    # url(r'^editschedule/(?P<scheduleid>\d+)$', views.edit_schedule, name='editschedule'),
    # url(r'^addschedule/(?P<taskid>\d+)$', views.new_schedule, name='addschedule'),
]

EdSurvey/home/views.py
from django.shortcuts import render


def index(request):
    return render(
        request,
        'home.htm',
    )

EdSurvey/home/templates/home.htm
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>EdSurvey</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
    <link rel="stylesheet" href="{% static 'main.css' %}" >
</head>
<body>

<div class="page-header">
    <h1><a href="/">Education by Survey</a></h1>
    <h6><i>Самый простой способ получить ответ - задать вопрос.</i></h6>
    <div align="right">
        {% if person %}
            Добро пожаловать, <a href="{% url 'clients:aka' %}">{{person}}</a>!
            ({{person.role}} в {{person.division}})
        {% else %}
            Кто ты такой, {{user}}?
        {% endif %}
        {% if user.username %}
            [ <a href="{% url 'logout' %}">выйти из {{user.username}}</a>]
        {% else %}
            [ <a href="{% url 'login' %}">Войти</a> ]
        {% endif %}
    </div>
    <a href="/questions/">Вопросы</a> |
    <a href="/querylists/">Опросники</a> |
    <a href="{% url 'schedules:task' %}">Задания</a> |
    <a href="{% url 'schedules:schedule' %}">Расписания</a> |
    <a href="/admin/" target="_blank">Админка</a> |
</div>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

{% block mainblock %}
    {% if person %}
        <h3>Добро пожаловать, {{person}}!</h3>
        <p>({{person.division}} от "{{person.division.client}}")</p>
    {% else %}
        <h3>Войдите как пользователь сайта, чтобы получить больше возможностей!</h3>
    {% endif %}

    {# ...тут будет дополнительная информация и новостная лента... #}
{% endblock %}
</div>
<br>
<hr border-color="#7b6b6b">
<footer class="page-footer">
    <br>
    <h6 align="center">
        <a href="https://github.com/EdSurvey/basefunc" target="_blank">EdSurvey на GitHub</a> |
        <a href="https://docs.djangoproject.com/en/1.11/contents/" target="_blank">Django Docs</a> |
        <a href="http://htmlbook.ru/html" target="_blank">Справочник HTML4</a> |
        <a href="http://htmlbook.ru/samhtml" target="_blank">Самоучитель HTML4</a> |
        <a href="http://htmlbook.ru/html5" target="_blank">HTML5</a> |
        <a href="https://webref.ru/css" target="_blank">Справочник CSS</a> |
        <a href="http://htmlbook.ru/samcss" target="_blank">Самоучитель CSS</a>
    </h6>
    <br>
</footer>
</body>
</html>