EdSurvey/EdSurvey/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from home.views import index as homepage
from clients.views import log_in, log_out

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', homepage, name='homepage'),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^login$', log_in, name='login'),
    url(r'^logout$', log_out, name='logout'),
    url(r'^clients/', include('clients.urls', namespace='clients')),
    url(r'^questions/', include('questions.urls', namespace='questions')),
    url(r'^querylists/', include('querylists.urls', namespace='querylists')),
    url(r'^schedules/', include('schedules.urls', namespace='schedules')),
]

EdSurvey/home/urls.py
from django.conf.urls import url, include

from . import views

#   home.urls


urlpatterns = [
    url(r'^$', views.index),
]

EdSurvey/querylists/urls.py
from django.conf.urls import url

from . import views

#   querylists.urls

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^editquerylist/(?P<querylistid>\d+)$', views.edit_querylist, name='editquerylist'),
    url(r'^newquerylist$', views.new_querylist, name='newquerylist'),
    url(r'^editqcontents/(?P<qcontentid>\d+)$', views.edit_qcontent, name='editqcontent'),
    url(r'^addqcontent/(?P<qlistid>\d+)$', views.new_qcontent, name='addqcontent'),
]

EdSurvey/querylists/models.py
from django.db.models.query_utils import Q
from django.db import models

from questions.models import Question
from clients.models import Division, Person

#   querylists.models


class QuerylistManager(models.Manager):

    @staticmethod
    def filter_expr(person):
        return Q(public=True) | (Q(owner=person) & Q(division=person.division))

    def all(self, person):
        return super().get_queryset().filter(self.filter_expr(person))


class QueryList(models.Model):
    name = models.CharField(max_length=60)
    description = models.TextField()
    division = models.ForeignKey(Division, on_delete=models.PROTECT)
    public = models.BooleanField(default=False)
    owner = models.ForeignKey(Person, on_delete=models.PROTECT, verbose_name='владелец')
    active = models.BooleanField('активный', default=True)
    archived = models.BooleanField('архивный', default=False)

    objects = models.Manager()
    with_perms = QuerylistManager()

    class Meta:
        verbose_name = 'Опросник'
        verbose_name_plural = 'Опросники'

    def __str__(self):
        return "{}.{}".format(self.id, self.name)


class QueryContent(models.Model):
    querylist = models.ForeignKey(QueryList, on_delete=models.PROTECT)
    question = models.ForeignKey(Question, on_delete=models.PROTECT)
    ordernum = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        verbose_name = 'Наполнение опросника'
        verbose_name_plural = 'Наполнение опросников'
        unique_together = ('querylist', 'question')

    def check_perm(self, person):
        return QueryList.with_perms.all(person).filter(pk=self.querylist.id)[:1].count() == 1

    def __str__(self):
        return "{}-{}".format(self.querylist, self.question)

EdSurvey/questions/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.db.models import Q

from clients.models import Division, Person


RADIOBUTTON = 'RB'  # (*) One -from- List
CHECKBOX = 'CB'  # [v] Some -from- List
LINKEDLISTS = 'LL'  # Link One from first list -to- One from other list
QUESTION_TYPE_CHOICES = (
    (RADIOBUTTON, 'Один из ...'),
    (CHECKBOX, 'Несколько из ...'),
    (LINKEDLISTS, "Путанка"),
)


class QuestionManager(models.Manager):

    @staticmethod
    def filter_expr(person):
        return Q(public=True) | (Q(owner=person) & Q(division=person.division))

    def all(self, person):
        return super().get_queryset().filter(self.filter_expr(person))


class Question(models.Model):
    name = models.CharField('наименование', max_length=60)
    description = models.TextField('полное описание')
    division = models.ForeignKey(Division, on_delete=models.PROTECT, verbose_name='организация')
    public = models.BooleanField('публичный', default=False)
    qtype = models.CharField(max_length=2,
                             choices=QUESTION_TYPE_CHOICES,
                             default=RADIOBUTTON,
                             verbose_name='Тип вопроса',
                             blank=True)
    owner = models.ForeignKey(Person, on_delete=models.PROTECT, verbose_name='личность-владелец')
    active = models.BooleanField('активный', default=True)
    archived = models.BooleanField('архивный', default=False)

    objects = models.Manager()
    with_perms = QuestionManager()

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'

    def __str__(self):
        return "{}.{}.{}".format(self.id, self.qtype, self.name)

    def __setstate__(self, state):
        self.name = state['name']
        self.description = state['description']
        self.qtype = state['qtype']
        self.public = state['public']
        self.active = state['active']
        self.division = state['division']
        self.owner = state['owner']


def question_pre_save(instance, **kwargs):
    # Проверка на изменение типа вопроса (qtype)
    # select 1 from Answer where Answer.question = self.id limit 1
    cntRB = AnswerRB.objects.all().filter(question=instance)[:1].count()
    cntCB = AnswerCB.objects.all().filter(question=instance)[:1].count()
    cntLL = AnswerLL.objects.all().filter(question=instance)[:1].count()
    if instance.qtype not in [qtype for (qtype, txt) in QUESTION_TYPE_CHOICES]:
        raise ValidationError(_("Unknown QType"))
    elif (instance.qtype == RADIOBUTTON and (cntCB + cntLL) > 0) or \
        (instance.qtype == CHECKBOX and (cntRB + cntLL) > 0) or \
        (instance.qtype == LINKEDLISTS and (cntRB + cntCB) > 0):
        raise ValidationError("Нельзя изменять тип вопроса, если вопрос всё ещё имеет ответы.")

pre_save.connect(question_pre_save, sender=Question)


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.PROTECT, verbose_name='вариант')
    content = models.TextField(verbose_name='вариант')
    ordernum = models.PositiveIntegerField(null=True, blank=True, verbose_name='порядок варианта')
    score = models.PositiveIntegerField(null=True, blank=True, verbose_name='балл')
    qtype = models.CharField(
        max_length=2,
        choices=QUESTION_TYPE_CHOICES,
        default=RADIOBUTTON,
        verbose_name = 'тип вопроса',
    )

    class Meta:
        verbose_name = 'Простой вариант'
        verbose_name_plural = 'Простые варианты'

    def __str__(self):
        return self.content

    def check_perm(self, person):
        return Question.with_perms.all(person).filter(pk=self.question.id)[:1].count() == 1

    def __getstate__(self):
        return {
            'content': self.content,
            'ordernum': self.ordernum,
            'score': self.score,
            'qtype': self.qtype,
        }

    def __setstate__(self, state):
        self.content, self.ordernum, self.score, self.qtype = \
            state['content'], state['ordernum'], state['score'], state['qtype']



def answer_pre_save(instance, **kwargs):
    instance.qtype = instance.question.qtype

pre_save.connect(answer_pre_save, sender=Answer)


class AnswerRB(Answer):
    """ qtype == RB
        необходим для создания отдельных валидаторов
    """
    answer = models.OneToOneField(
        Answer, on_delete=models.CASCADE,
        parent_link=True,
    )

    class Meta:
        verbose_name = 'Одиночный вариант (RadioButton)'
        verbose_name_plural = 'Одиночные варианты (RadioButton)'

    def clean(self):
        qtype = self.question.qtype
        if qtype != 'RB':
            raise ValidationError("Тип вопроса ({}) и тип ответа (RB) не совпадают.".format(qtype))


class AnswerCB(Answer):
    """ qtype == CB
        необходим для создания отдельных валидаторов
    """
    answer = models.OneToOneField(
        Answer, on_delete=models.CASCADE,
        parent_link=True,
    )

    class Meta:
        verbose_name = 'Множественный вариант (CheckBox)'
        verbose_name_plural = 'Множественные варианты (CheckBox)'

    def clean(self):
        qtype = self.question.qtype
        if qtype != 'CB':
            raise ValidationError("Тип вопроса ({}) и тип ответа (CB) не совпадают.".format(qtype))


class AnswerLL(Answer):
    answer = models.OneToOneField(
        Answer, on_delete=models.CASCADE,
        parent_link=True,
    )
    linkeditem = models.TextField(verbose_name='ответ')
    ordernumitem = models.PositiveIntegerField(null=True, blank=True, verbose_name='порядок ответа')

    class Meta:
        verbose_name = 'Ответ-Путанка'
        verbose_name_plural = 'Ответы-Путанки'

    def clean(self):
        qtype = self.question.qtype
        if qtype != 'LL':
            raise ValidationError("Тип вопроса ({}) и тип ответа (LL) не совпадают.".format(qtype))

    def __getstate__(self):
        result = super().__getstate__()
        result['linkeditem'] = self.linkeditem
        result['ordernumitem'] = self.ordernumitem
        return result

    def __setstate__(self, state):
        self.linkeditem, self.ordernumitem = \
            state['linkeditem'], state['ordernumitem']


def get_answer_class(qtype):
    if qtype == 'LL':
        return AnswerLL
    elif qtype == 'RB':
        return AnswerRB
    elif qtype == 'CB':
        return AnswerCB


def copy_answers(source, target):
    """ Copy answers of source Question to target Question

    :param source: saved Question
    :param target: sqved Question
    :return:
    """
    answer_class = get_answer_class(source.qtype)
    for source_answer in answer_class.objects.filter(question=source):
        # Create new instance of Answer*
        target_answer = answer_class()
        # Link create new instance of Answer* to target Question
        target_answer.question = target
        # Copy source attribute values into target ones
        target_answer.__setstate__(source_answer.__getstate__())
        target_answer.save()

EdSurvey/querylists/forms.py
from django.forms import ModelForm

from .models import QueryList, QueryContent

#   querylists.forms


class EditQueryListForm(ModelForm):
    class Meta:
        model = QueryList
        fields = ['name', 'description', 'public', 'active', 'archived']   # , 'division', 'owner']

    def __init__(self, *args, **kwargs):
        if 'readonly' in kwargs:
            self.readonly = kwargs.pop('readonly')
        else:
            self.readonly = False
        if 'contents' in kwargs:
            self.answers = kwargs.pop('contents')
        else:
            self.contents = None

        super().__init__(*args, **kwargs)

        instance = getattr(self, 'instance', None)
        if instance and instance.pk and self.readonly:
            for field in self.fields:
                self.fields[field].widget.attrs['disabled'] = True


class EditQueryContentForm(ModelForm):
    class Meta:
        model = QueryContent
        fields = ['ordernum', 'question']

EdSurvey/querylists/templates/editqcontent.html
{% extends 'home.htm' %}
{% block mainblock %}

<h2>Варианты ответов на вопрос:</h2>
<h3>Вопрос: {{question.name}}</h3>
<h3 >Задание: {{question.description|linebreaks}}</h3>

<form method="post">
    {{form.as_p}}
    {% csrf_token %}
    <input type="submit" value="Сохранить" name="save" {% if readonly %}disabled{% endif %}>
    <input type="submit" value="Удалить" name="del" {% if not qcontent.id or readonly %}disabled{% endif %}>
    <input type="submit" value="К вопросу" name="cancel">
</form>

{% endblock %}

EdSurvey/querylists/templates/editqlist.html
{% extends 'home.htm' %}
{% block mainblock %}

<h2>Опросник:</h2>

<form method="post">
    {{form.as_p}}
    {% csrf_token %}
    <div>
        <input type="submit" value="Сохранить" name="save" {% if readonly %}disabled{% endif %}>
        <input type="submit" value="Скопировать" name="copy" {% if not querylist.id %}disabled{% endif %}>
        <input type="submit" value="Удалить" name="del" {% if not querylist.id or readonly %}disabled{% endif %}>
        <input type="submit" value="К опросникам" name="cancel">
    </div>
</form>

    {% block qcontentsblock %}
        {{qcontentsblock}}
    {% endblock%}
    {% if querylist.id and not readonly %}<a href="{% url 'querylists:addqcontent' querylist.id %}"> Добавить вопросы в Опросник >> </a>{% endif %}

{% endblock %}

EdSurvey/querylists/templates/qcontentsblock.html
{% block answersblock %}

<h3>Варианты ответов:</h3>
<table border="1">
    <tr bgcolor="#FFA500">
        <th>Порядок</th>
        <th>Вопрос</th>
        <th>Тип вопроса</th>
        <th>Владелец</th>
        <th>Организация</th>
    </tr>
{% for qcontent in qcontents %}
    <tr>
        <td>{% if qcontent.ordernum %}{{qcontent.ordernum}}{% else %}-{% endif %}</td>
        <td><a href="{% url 'querylists:editqcontent' qcontent.id %}">{{qcontent.question.name}}</a></td>
        <td>{{qcontent.question.get_qtype_display}}</td>
        <td>{{qcontent.question.owner}}</td>
        <td>{{qcontent.question.division}}</td>
    </tr>
{% endfor%}
</table>

{% endblock %}

EdSurvey/querylists/templates/qlistsfilterblock.html
    <div>
        <input type="submit" value="Все" name="set_all">
        <input type="submit" value="Сбросить" name="default">

        <input type="checkbox" name="choice_pub" id="choice_pub" value="pub"
               {% if flt_q_pub %} checked {% endif %}
        />
        <label for="choice_pub">Публичные</label>

        <input type="checkbox" name="choice_own" id="choice_own" value="own"
               {% if flt_q_own %} checked {% endif %}
        />
        <label for="choice_own">Мои</label>

        <input type="checkbox" name="choice_oth" id="choice_oth" value="oth"
               {% if flt_q_oth %} checked {% endif %}
        />
        <label for="choice_oth">Другие</label>

        <input type="checkbox" name="choice_act" id="choice_act" value="act"
               {% if flt_q_act %} checked {% endif %}
        />
        <label for="choice_act">Активные</label>

        <input type="checkbox" name="choice_hid" id="choice_hid" value="hid"
               {% if flt_q_hid %} checked {% endif %}
        />
        <label for="choice_hid">Скрытые</label>

        <input type="checkbox" name="choice_arc" id="choice_arc" value="arc"
               {% if flt_q_arc %} checked {% endif %}
        />
        <label for="choice_arc">Архивные</label>

        <input type="submit" value="Показать" name="filter">
    </div>

    <hr border-color="#7b6b6b">

EdSurvey/querylists/templates/querylists.html
{% extends 'home.htm' %}
{% block mainblock %}
    <h1>Опросники</h1>

<form action="{% url 'querylists:index' %}" method="post">
    {% csrf_token %}

    {% block resultblock %}
        {{querylists_filter_block}}
    {% endblock %}

    <table border="1">
        <tr bgcolor="#FFA500">
            <th>Public</th>
            <th>Название</th>
            <th>Описание</th>
            <th>Владелец</th>
            <th>Организация</th>
        </tr>
    {% for querylist in querylists %}
        <tr
                {% if not querylist.active %} bgcolor="Tan"{% endif %}
                {% if querylist.archived %} style="color: red" {% endif %}
        >
            <td>{% if querylist.public %} Да {% else %} Нет {% endif %}</td>
            <td><a href="{% url 'querylists:editquerylist' querylist.id %}">{{querylist.name}} >></a></td>
            <td>{{querylist.description}}</td>
            <td>{{querylist.owner}}</td>
            <td>{{querylist.division}}</td>
        </tr>
    {% endfor %}
    </table>

    <input type="submit" value="Новый Опросник" name="new">

</form>
{% endblock %}